inherit_from: .rubocop_todo.yml

AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'script/**/*'
    - 'test/**'
    - 'db/schema.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Documentation:
  Enabled: false